name: smartassistant
description: "Smart Assistant Warehouse Area 3"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0

  english_words: ^4.0.0
  provider: ^6.0.0

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar: ^6.2.1
  intl: ^0.19.0
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  file_picker: ^8.1.2
  firebase_storage: ^11.6.0
  flutter_datetime_picker: ^1.5.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/logopg.png
      - assets/logogd.png
      - assets/loginbg.jpg
      - assets/bgdb.jpeg
      - assets/penugasan.png
      - assets/comdev.png
      - assets/disposisi.png
      - assets/pengajuan.png
      - assets/laporan.png
      - assets/teamwork.png
      - assets/project.png
      - assets/konsultasi.png
  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Bold.ttf
          - asset: assets/fonts/Poppins-Medium.ttf