// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABFFvmIkQSJVJfZXjY_okAgw3udYJugpk',
    appId: '1:872161769698:web:014cc3aa51a761fe4f86bb',
    messagingSenderId: '872161769698',
    projectId: 'smart-assistant-gudang-iii',
    authDomain: 'smart-assistant-gudang-iii.firebaseapp.com',
    storageBucket: 'smart-assistant-gudang-iii.appspot.com',
    measurementId: 'G-0YJMPN7S84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyQxWtqb_9lsILnhUDKuHBsO-ULqvVeCs',
    appId: '1:872161769698:android:308a3b809fa223014f86bb',
    messagingSenderId: '872161769698',
    projectId: 'smart-assistant-gudang-iii',
    storageBucket: 'smart-assistant-gudang-iii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoXdqGOsRnsAZJkI3S77tFEXauUl8bK7w',
    appId: '1:872161769698:ios:7e8ac3c4892587894f86bb',
    messagingSenderId: '872161769698',
    projectId: 'smart-assistant-gudang-iii',
    storageBucket: 'smart-assistant-gudang-iii.appspot.com',
    iosBundleId: 'com.example.smartassistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoXdqGOsRnsAZJkI3S77tFEXauUl8bK7w',
    appId: '1:872161769698:ios:7e8ac3c4892587894f86bb',
    messagingSenderId: '872161769698',
    projectId: 'smart-assistant-gudang-iii',
    storageBucket: 'smart-assistant-gudang-iii.appspot.com',
    iosBundleId: 'com.example.smartassistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABFFvmIkQSJVJfZXjY_okAgw3udYJugpk',
    appId: '1:872161769698:web:8048482123c1c51c4f86bb',
    messagingSenderId: '872161769698',
    projectId: 'smart-assistant-gudang-iii',
    authDomain: 'smart-assistant-gudang-iii.firebaseapp.com',
    storageBucket: 'smart-assistant-gudang-iii.appspot.com',
    measurementId: 'G-JM2E7FTGF6',
  );
}
